/**
 * One-click application templates.
 *
 * A template is an ordinary image-sourced application plus the databases it
 * needs: installing one creates the services, links them with a prefix and
 * writes the app's variables as `${PREFIX_…}` references to the link
 * variables, so credentials are never copied and rotate with the service.
 * Everything a template creates stays editable afterwards like any other app.
 *
 * Only images that run as a single container (plus the linked databases)
 * qualify: no sidecars, no host mounts, no published ports besides HTTP.
 * Images and tags were checked against their registries; ports, volumes and
 * variables follow each project's own container documentation.
 */
import { randomBytes } from 'node:crypto';
import type { ServiceType, TemplateAccess, TemplateCategory } from '@ploy/shared';
import { generateToken } from '../lib/crypto.ts';

export interface TemplateContext {
  /** Public base URL without a trailing slash, or null when the app has no domain. */
  url: string | null;
  host: string | null;
  https: boolean;
  /** Email of the installing user (initial admin account where an image needs one). */
  email: string;
  timezone: string;
  /** A random alphanumeric secret, safe inside URLs and shell-free env values. */
  secret: (length?: number) => string;
  /** `bytes` random bytes as lowercase hex (images that insist on hex keys). */
  hex: (bytes: number) => string;
  /** `bytes` random bytes as standard base64 (Laravel `APP_KEY`, Phoenix secrets). */
  base64: (bytes: number) => string;
}

export interface TemplateService {
  /** Suffix of the service name (`n8n-db`). */
  key: string;
  type: ServiceType;
  version?: string;
  /** Link prefix: the app reads `${DB_PGHOST}` and friends. */
  prefix: string;
}

export interface TemplateDefinition {
  id: string;
  name: string;
  category: TemplateCategory;
  website: string;
  image: string;
  port: number;
  volumes: readonly { name: string; mountPath: string }[];
  services: readonly TemplateService[];
  /** The app needs to know its public URL (absolute links, cookies, webhooks). */
  needsUrl: boolean;
  healthCheckPath: string | null;
  healthCheckTimeoutSec: number;
  /** Memory the app needs to run comfortably, shown before installing. */
  memoryMb: number;
  access: TemplateAccess;
  /** Shown first in the gallery. */
  featured?: boolean;
  /** Start command (`sh -c`) when the image's own entrypoint needs arguments; `$VAR` is expanded by the shell at start. */
  command?: string;
  env: (t: TemplateContext) => Record<string, string>;
}

export function templateSecret(length = 32): string {
  let out = '';
  while (out.length < length) out += generateToken(length).replace(/[^A-Za-z0-9]/g, '');
  return out.slice(0, length);
}

export function templateHex(bytes: number): string {
  return randomBytes(bytes).toString('hex');
}

export function templateBase64(bytes: number): string {
  return randomBytes(bytes).toString('base64');
}

// ----------------------------------------------------------------- services

const postgres = (key = 'db', prefix = 'DB_'): TemplateService => ({ key, type: 'postgres', version: '17', prefix });
const mariadb = (key = 'db', prefix = 'DB_'): TemplateService => ({ key, type: 'mariadb', version: '11.8', prefix });
const mysql = (key = 'db', prefix = 'DB_'): TemplateService => ({ key, type: 'mysql', version: '8.4', prefix });
const mongo = (version = '8.0', key = 'db', prefix = 'DB_'): TemplateService => ({ key, type: 'mongo', version, prefix });
const redis = (key = 'redis', prefix = 'CACHE_'): TemplateService => ({ key, type: 'redis', version: '8', prefix });
const clickhouse = (key = 'events', prefix = 'CH_'): TemplateService => ({ key, type: 'clickhouse', version: '25.8', prefix });

/** Link variables, as the app's env references them (resolved at deploy time). */
const pg = {
  host: '${DB_PGHOST}',
  port: '${DB_PGPORT}',
  database: '${DB_PGDATABASE}',
  user: '${DB_PGUSER}',
  password: '${DB_PGPASSWORD}',
  url: '${DB_DATABASE_URL}',
  hostPort: '${DB_PGHOST}:${DB_PGPORT}',
  jdbc: 'jdbc:postgresql://${DB_PGHOST}:${DB_PGPORT}/${DB_PGDATABASE}',
};
const my = {
  host: '${DB_MYSQL_HOST}',
  port: '${DB_MYSQL_PORT}',
  database: '${DB_MYSQL_DATABASE}',
  user: '${DB_MYSQL_USER}',
  password: '${DB_MYSQL_PASSWORD}',
  url: '${DB_DATABASE_URL}',
  hostPort: '${DB_MYSQL_HOST}:${DB_MYSQL_PORT}',
};
const cache = { url: '${CACHE_REDIS_URL}', host: '${CACHE_REDIS_HOST}', port: '${CACHE_REDIS_PORT}', password: '${CACHE_REDIS_PASSWORD}' };
const mongoUrl = '${DB_MONGO_URL}';
const ch = { url: '${CH_CLICKHOUSE_URL}' };

const linuxserver = (t: TemplateContext) => ({ PUID: '1000', PGID: '1000', TZ: t.timezone });
/** Laravel-style key: `base64:` plus 32 random bytes. */
const laravelKey = (t: TemplateContext) => `base64:${t.base64(32)}`;
/** `{ KEY: url }` only when the app has an address (templates that merely prefer to know it). */
const urlEnv = (t: TemplateContext, key: string): Record<string, string> => (t.url === null ? {} : { [key]: t.url });

const defaults = { volumes: [], services: [], needsUrl: false, healthCheckPath: null, healthCheckTimeoutSec: 180 } as const;

export const TEMPLATES: readonly TemplateDefinition[] = [
  // =============================================================== automation
  {
    ...defaults,
    id: 'n8n',
    name: 'n8n',
    category: 'automation',
    website: 'https://n8n.io',
    image: 'n8nio/n8n:stable',
    port: 5678,
    volumes: [{ name: 'n8n', mountPath: '/home/node/.n8n' }],
    services: [postgres()],
    needsUrl: true,
    healthCheckPath: '/healthz',
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'setup' },
    featured: true,
    env: (t) => ({
      DB_TYPE: 'postgresdb',
      DB_POSTGRESDB_HOST: pg.host,
      DB_POSTGRESDB_PORT: pg.port,
      DB_POSTGRESDB_DATABASE: pg.database,
      DB_POSTGRESDB_USER: pg.user,
      DB_POSTGRESDB_PASSWORD: pg.password,
      N8N_ENCRYPTION_KEY: t.secret(32),
      N8N_HOST: t.host ?? '',
      N8N_PORT: '5678',
      N8N_PROTOCOL: t.https ? 'https' : 'http',
      WEBHOOK_URL: `${t.url}/`,
      N8N_PROXY_HOPS: '1',
      // n8n refuses to set its session cookie over plain HTTP unless told otherwise.
      N8N_SECURE_COOKIE: String(t.https),
      N8N_RUNNERS_ENABLED: 'true',
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true',
      GENERIC_TIMEZONE: t.timezone,
      TZ: t.timezone,
    }),
  },
  {
    ...defaults,
    id: 'node-red',
    name: 'Node-RED',
    category: 'automation',
    website: 'https://nodered.org',
    image: 'nodered/node-red:latest',
    port: 1880,
    volumes: [{ name: 'data', mountPath: '/data' }],
    memoryMb: 256,
    // The editor is open until adminAuth is set in settings.js; the card says so.
    access: { kind: 'open' },
    env: (t) => ({ TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'activepieces',
    name: 'Activepieces',
    category: 'automation',
    website: 'https://www.activepieces.com',
    image: 'ghcr.io/activepieces/activepieces:latest',
    port: 80,
    volumes: [{ name: 'cache', mountPath: '/usr/src/app/cache' }],
    services: [postgres(), redis()],
    needsUrl: true,
    healthCheckPath: '/api/v1/flags',
    healthCheckTimeoutSec: 300,
    memoryMb: 1024,
    access: { kind: 'setup' },
    env: (t) => ({
      AP_ENVIRONMENT: 'prod',
      AP_FRONTEND_URL: t.url ?? '',
      AP_ENCRYPTION_KEY: t.hex(16),
      AP_JWT_SECRET: t.secret(32),
      AP_EXECUTION_MODE: 'UNSANDBOXED',
      AP_QUEUE_MODE: 'REDIS',
      AP_DB_TYPE: 'POSTGRES',
      AP_POSTGRES_HOST: pg.host,
      AP_POSTGRES_PORT: pg.port,
      AP_POSTGRES_DATABASE: pg.database,
      AP_POSTGRES_USERNAME: pg.user,
      AP_POSTGRES_PASSWORD: pg.password,
      AP_REDIS_HOST: cache.host,
      AP_REDIS_PORT: cache.port,
      AP_REDIS_PASSWORD: cache.password,
      AP_TELEMETRY_ENABLED: 'false',
    }),
  },
  {
    ...defaults,
    id: 'windmill',
    name: 'Windmill',
    category: 'automation',
    website: 'https://www.windmill.dev',
    image: 'ghcr.io/windmill-labs/windmill:main',
    port: 8000,
    volumes: [{ name: 'worker', mountPath: '/tmp/windmill' }],
    services: [postgres()],
    needsUrl: true,
    healthCheckPath: '/api/version',
    healthCheckTimeoutSec: 300,
    memoryMb: 1024,
    access: { kind: 'default', user: 'admin@windmill.dev', password: 'changeme' },
    env: (t) => ({ DATABASE_URL: pg.url, MODE: 'standalone', BASE_URL: t.url ?? '' }),
  },

  // =============================================================== monitoring
  {
    ...defaults,
    id: 'uptime-kuma',
    name: 'Uptime Kuma',
    category: 'monitoring',
    website: 'https://uptime.kuma.pet',
    image: 'louislam/uptime-kuma:2',
    port: 3001,
    volumes: [{ name: 'data', mountPath: '/app/data' }],
    memoryMb: 256,
    access: { kind: 'setup' },
    featured: true,
    env: (t) => ({ TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'grafana',
    name: 'Grafana',
    category: 'monitoring',
    website: 'https://grafana.com/oss/grafana',
    image: 'grafana/grafana:latest',
    port: 3000,
    volumes: [{ name: 'data', mountPath: '/var/lib/grafana' }],
    healthCheckPath: '/api/health',
    memoryMb: 256,
    access: { kind: 'login', user: 'admin', passwordKey: 'GF_SECURITY_ADMIN_PASSWORD' },
    featured: true,
    env: (t) => ({
      GF_SECURITY_ADMIN_USER: 'admin',
      GF_SECURITY_ADMIN_PASSWORD: t.secret(20),
      ...urlEnv(t, 'GF_SERVER_ROOT_URL'),
      GF_ANALYTICS_REPORTING_ENABLED: 'false',
    }),
  },
  {
    ...defaults,
    id: 'prometheus',
    name: 'Prometheus',
    category: 'monitoring',
    website: 'https://prometheus.io',
    image: 'prom/prometheus:latest',
    port: 9090,
    volumes: [{ name: 'data', mountPath: '/prometheus' }],
    healthCheckPath: '/-/healthy',
    memoryMb: 256,
    access: { kind: 'open' },
    env: () => ({}),
  },
  {
    ...defaults,
    id: 'healthchecks',
    name: 'Healthchecks',
    category: 'monitoring',
    website: 'https://healthchecks.io',
    image: 'healthchecks/healthchecks:latest',
    port: 8000,
    services: [postgres()],
    needsUrl: true,
    healthCheckPath: '/api/v1/status/',
    healthCheckTimeoutSec: 300,
    memoryMb: 256,
    access: { kind: 'setup' },
    env: (t) => ({
      DB: 'postgres',
      DB_HOST: pg.host,
      DB_PORT: pg.port,
      DB_NAME: pg.database,
      DB_USER: pg.user,
      DB_PASSWORD: pg.password,
      SECRET_KEY: t.secret(48),
      SITE_ROOT: t.url ?? '',
      SITE_NAME: 'Healthchecks',
      ALLOWED_HOSTS: '*',
      REGISTRATION_OPEN: 'True',
      DEBUG: 'False',
    }),
  },
  {
    ...defaults,
    id: 'beszel',
    name: 'Beszel',
    category: 'monitoring',
    website: 'https://beszel.dev',
    image: 'henrygd/beszel:latest',
    port: 8090,
    volumes: [{ name: 'data', mountPath: '/beszel_data' }],
    healthCheckPath: '/api/health',
    memoryMb: 64,
    access: { kind: 'setup' },
    env: (t) => ({ TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'changedetection',
    name: 'changedetection.io',
    category: 'monitoring',
    website: 'https://changedetection.io',
    image: 'ghcr.io/dgtlmoon/changedetection.io:latest',
    port: 5000,
    volumes: [{ name: 'datastore', mountPath: '/datastore' }],
    memoryMb: 256,
    access: { kind: 'open' },
    env: (t) => ({ ...urlEnv(t, 'BASE_URL'), TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'speedtest-tracker',
    name: 'Speedtest Tracker',
    category: 'monitoring',
    website: 'https://docs.speedtest-tracker.dev',
    image: 'lscr.io/linuxserver/speedtest-tracker:latest',
    port: 80,
    volumes: [{ name: 'config', mountPath: '/config' }],
    healthCheckPath: '/api/healthcheck',
    healthCheckTimeoutSec: 300,
    memoryMb: 256,
    access: { kind: 'default', user: 'admin@example.com', password: 'password' },
    env: (t) => ({
      ...linuxserver(t),
      APP_KEY: laravelKey(t),
      ...urlEnv(t, 'APP_URL'),
      APP_TIMEZONE: t.timezone,
      DB_CONNECTION: 'sqlite',
      SPEEDTEST_SCHEDULE: '0 * * * *',
    }),
  },
  {
    ...defaults,
    id: 'openobserve',
    name: 'OpenObserve',
    category: 'monitoring',
    website: 'https://openobserve.ai',
    image: 'public.ecr.aws/zinclabs/openobserve:latest',
    port: 5080,
    volumes: [{ name: 'data', mountPath: '/data' }],
    healthCheckPath: '/healthz',
    memoryMb: 512,
    access: { kind: 'login', user: { key: 'ZO_ROOT_USER_EMAIL' }, passwordKey: 'ZO_ROOT_USER_PASSWORD' },
    env: (t) => ({ ZO_ROOT_USER_EMAIL: t.email, ZO_ROOT_USER_PASSWORD: t.secret(20), ZO_DATA_DIR: '/data', ZO_TELEMETRY: 'false' }),
  },

  // ================================================================ analytics
  {
    ...defaults,
    id: 'umami',
    name: 'Umami',
    category: 'analytics',
    website: 'https://umami.is',
    image: 'ghcr.io/umami-software/umami:3',
    port: 3000,
    services: [postgres()],
    healthCheckPath: '/api/heartbeat',
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    // Umami seeds a fixed first account; the UI tells the user to change it at once.
    access: { kind: 'default', user: 'admin', password: 'umami' },
    featured: true,
    env: (t) => ({ DATABASE_URL: pg.url, APP_SECRET: t.secret(48) }),
  },
  {
    ...defaults,
    id: 'plausible',
    name: 'Plausible',
    category: 'analytics',
    website: 'https://plausible.io',
    image: 'ghcr.io/plausible/community-edition:v3',
    port: 8000,
    services: [postgres(), clickhouse()],
    needsUrl: true,
    healthCheckPath: '/api/health',
    healthCheckTimeoutSec: 600,
    memoryMb: 1024,
    access: { kind: 'setup' },
    // The image's entrypoint only runs the server; the schema is created and migrated first.
    command: '/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run',
    env: (t) => ({
      BASE_URL: t.url ?? '',
      SECRET_KEY_BASE: t.base64(64),
      TOTP_VAULT_KEY: t.base64(32),
      DATABASE_URL: pg.url,
      CLICKHOUSE_DATABASE_URL: ch.url,
      DISABLE_REGISTRATION: 'false',
    }),
  },
  {
    ...defaults,
    id: 'matomo',
    name: 'Matomo',
    category: 'analytics',
    website: 'https://matomo.org',
    image: 'matomo:5-apache',
    port: 80,
    volumes: [{ name: 'html', mountPath: '/var/www/html' }],
    services: [mariadb()],
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'setup' },
    env: () => ({
      MATOMO_DATABASE_HOST: my.host,
      MATOMO_DATABASE_PORT: my.port,
      MATOMO_DATABASE_ADAPTER: 'mysql',
      MATOMO_DATABASE_USERNAME: my.user,
      MATOMO_DATABASE_PASSWORD: my.password,
      MATOMO_DATABASE_DBNAME: my.database,
    }),
  },
  {
    ...defaults,
    id: 'metabase',
    name: 'Metabase',
    category: 'analytics',
    website: 'https://www.metabase.com',
    image: 'metabase/metabase:latest',
    port: 3000,
    services: [postgres()],
    healthCheckPath: '/api/health',
    // The JVM and the first migration run take a while on small servers.
    healthCheckTimeoutSec: 600,
    memoryMb: 1536,
    access: { kind: 'setup' },
    env: (t) => ({
      MB_DB_TYPE: 'postgres',
      MB_DB_HOST: pg.host,
      MB_DB_PORT: pg.port,
      MB_DB_DBNAME: pg.database,
      MB_DB_USER: pg.user,
      MB_DB_PASS: pg.password,
      ...urlEnv(t, 'MB_SITE_URL'),
      JAVA_TIMEZONE: t.timezone,
    }),
  },

  // ====================================================================== cms
  {
    ...defaults,
    id: 'wordpress',
    name: 'WordPress',
    category: 'cms',
    website: 'https://wordpress.org',
    image: 'wordpress:6-apache',
    port: 80,
    volumes: [{ name: 'html', mountPath: '/var/www/html' }],
    services: [mariadb()],
    memoryMb: 512,
    access: { kind: 'setup' },
    featured: true,
    // The image's wp-config honours X-Forwarded-Proto, so HTTPS behind the proxy works as is.
    env: () => ({
      WORDPRESS_DB_HOST: my.hostPort,
      WORDPRESS_DB_USER: my.user,
      WORDPRESS_DB_PASSWORD: my.password,
      WORDPRESS_DB_NAME: my.database,
    }),
  },
  {
    ...defaults,
    id: 'ghost',
    name: 'Ghost',
    category: 'cms',
    website: 'https://ghost.org',
    image: 'ghost:6-alpine',
    port: 2368,
    volumes: [{ name: 'content', mountPath: '/var/lib/ghost/content' }],
    services: [mysql()],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'setup', path: '/ghost' },
    featured: true,
    env: (t) => ({
      url: t.url ?? '',
      database__client: 'mysql',
      database__connection__host: my.host,
      database__connection__port: my.port,
      database__connection__user: my.user,
      database__connection__password: my.password,
      database__connection__database: my.database,
    }),
  },
  {
    ...defaults,
    id: 'directus',
    name: 'Directus',
    category: 'cms',
    website: 'https://directus.io',
    image: 'directus/directus:11',
    port: 8055,
    volumes: [{ name: 'uploads', mountPath: '/directus/uploads' }],
    services: [postgres()],
    needsUrl: true,
    healthCheckPath: '/server/health',
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'login', user: { key: 'ADMIN_EMAIL' }, passwordKey: 'ADMIN_PASSWORD' },
    env: (t) => ({
      SECRET: t.secret(48),
      ADMIN_EMAIL: t.email,
      ADMIN_PASSWORD: t.secret(20),
      DB_CLIENT: 'pg',
      DB_HOST: pg.host,
      DB_PORT: pg.port,
      DB_DATABASE: pg.database,
      DB_USER: pg.user,
      DB_PASSWORD: pg.password,
      PUBLIC_URL: t.url ?? '',
    }),
  },
  {
    ...defaults,
    id: 'joomla',
    name: 'Joomla',
    category: 'cms',
    website: 'https://www.joomla.org',
    image: 'joomla:5-apache',
    port: 80,
    volumes: [{ name: 'html', mountPath: '/var/www/html' }],
    services: [mariadb()],
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'login', user: 'admin', passwordKey: 'JOOMLA_ADMIN_PASSWORD', path: '/administrator' },
    env: (t) => ({
      JOOMLA_DB_HOST: my.hostPort,
      JOOMLA_DB_USER: my.user,
      JOOMLA_DB_PASSWORD: my.password,
      JOOMLA_DB_NAME: my.database,
      JOOMLA_SITE_NAME: 'Joomla',
      JOOMLA_ADMIN_USER: 'Administrator',
      JOOMLA_ADMIN_USERNAME: 'admin',
      JOOMLA_ADMIN_PASSWORD: t.secret(16),
      JOOMLA_ADMIN_EMAIL: t.email,
    }),
  },
  {
    ...defaults,
    id: 'drupal',
    name: 'Drupal',
    category: 'cms',
    website: 'https://www.drupal.org',
    image: 'drupal:11-apache',
    port: 80,
    volumes: [{ name: 'html', mountPath: '/var/www/html' }],
    services: [postgres()],
    memoryMb: 512,
    // Drupal's installer asks for the database itself; the linked service's page has the details.
    access: { kind: 'setup', database: true },
    env: () => ({}),
  },
  {
    ...defaults,
    id: 'flarum',
    name: 'Flarum',
    category: 'cms',
    website: 'https://flarum.org',
    image: 'mondedie/flarum:stable',
    port: 8888,
    volumes: [
      { name: 'extensions', mountPath: '/flarum/app/extensions' },
      { name: 'assets', mountPath: '/flarum/app/public/assets' },
    ],
    services: [mariadb()],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 256,
    access: { kind: 'login', user: 'admin', passwordKey: 'FLARUM_ADMIN_PASS' },
    env: (t) => ({
      DEBUG: 'false',
      FORUM_URL: t.url ?? '',
      DB_HOST: my.host,
      DB_PORT: my.port,
      DB_NAME: my.database,
      DB_USER: my.user,
      DB_PASS: my.password,
      FLARUM_ADMIN_USER: 'admin',
      FLARUM_ADMIN_PASS: t.secret(16),
      FLARUM_ADMIN_MAIL: t.email,
      FLARUM_TITLE: 'Flarum',
    }),
  },
  {
    ...defaults,
    id: 'wikijs',
    name: 'Wiki.js',
    category: 'cms',
    website: 'https://js.wiki',
    image: 'ghcr.io/requarks/wiki:2',
    port: 3000,
    services: [postgres()],
    healthCheckPath: '/healthz',
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'setup' },
    env: () => ({ DB_TYPE: 'postgres', DB_HOST: pg.host, DB_PORT: pg.port, DB_USER: pg.user, DB_PASS: pg.password, DB_NAME: pg.database }),
  },
  {
    ...defaults,
    id: 'bookstack',
    name: 'BookStack',
    category: 'cms',
    website: 'https://www.bookstackapp.com',
    image: 'lscr.io/linuxserver/bookstack:latest',
    port: 80,
    volumes: [{ name: 'config', mountPath: '/config' }],
    services: [mariadb()],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'default', user: 'admin@admin.com', password: 'password' },
    env: (t) => ({
      ...linuxserver(t),
      APP_URL: t.url ?? '',
      APP_KEY: laravelKey(t),
      DB_HOST: my.host,
      DB_PORT: my.port,
      DB_USERNAME: my.user,
      DB_PASSWORD: my.password,
      DB_DATABASE: my.database,
    }),
  },
  {
    ...defaults,
    id: 'dokuwiki',
    name: 'DokuWiki',
    category: 'cms',
    website: 'https://www.dokuwiki.org',
    image: 'lscr.io/linuxserver/dokuwiki:latest',
    port: 80,
    volumes: [{ name: 'config', mountPath: '/config' }],
    memoryMb: 128,
    access: { kind: 'setup', path: '/install.php' },
    env: (t) => linuxserver(t),
  },

  // ============================================================= productivity
  {
    ...defaults,
    id: 'nocodb',
    name: 'NocoDB',
    category: 'productivity',
    website: 'https://nocodb.com',
    image: 'nocodb/nocodb:latest',
    port: 8080,
    volumes: [{ name: 'data', mountPath: '/usr/app/data' }],
    services: [postgres()],
    healthCheckPath: '/api/v1/health',
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'setup' },
    featured: true,
    env: (t) => ({
      NC_DB: `pg://${pg.host}:${pg.port}?u=${pg.user}&p=${pg.password}&d=${pg.database}`,
      NC_AUTH_JWT_SECRET: t.secret(48),
      ...urlEnv(t, 'NC_PUBLIC_URL'),
    }),
  },
  {
    ...defaults,
    id: 'baserow',
    name: 'Baserow',
    category: 'productivity',
    website: 'https://baserow.io',
    image: 'baserow/baserow:latest',
    port: 80,
    volumes: [{ name: 'data', mountPath: '/baserow/data' }],
    needsUrl: true,
    healthCheckPath: '/api/_health/',
    healthCheckTimeoutSec: 600,
    memoryMb: 2048,
    access: { kind: 'setup' },
    env: (t) => ({ BASEROW_PUBLIC_URL: t.url ?? '' }),
  },
  {
    ...defaults,
    id: 'docmost',
    name: 'Docmost',
    category: 'productivity',
    website: 'https://docmost.com',
    image: 'docmost/docmost:latest',
    port: 3000,
    volumes: [{ name: 'storage', mountPath: '/app/data/storage' }],
    services: [postgres(), redis()],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'setup' },
    env: (t) => ({ APP_URL: t.url ?? '', APP_SECRET: t.secret(48), DATABASE_URL: pg.url, REDIS_URL: cache.url }),
  },
  {
    ...defaults,
    id: 'vikunja',
    name: 'Vikunja',
    category: 'productivity',
    website: 'https://vikunja.io',
    image: 'vikunja/vikunja:latest',
    port: 3456,
    volumes: [{ name: 'files', mountPath: '/app/vikunja/files' }],
    services: [postgres()],
    needsUrl: true,
    healthCheckPath: '/api/v1/info',
    memoryMb: 256,
    access: { kind: 'setup' },
    env: (t) => ({
      VIKUNJA_DATABASE_TYPE: 'postgres',
      VIKUNJA_DATABASE_HOST: pg.hostPort,
      VIKUNJA_DATABASE_USER: pg.user,
      VIKUNJA_DATABASE_PASSWORD: pg.password,
      VIKUNJA_DATABASE_DATABASE: pg.database,
      VIKUNJA_SERVICE_JWTSECRET: t.secret(48),
      VIKUNJA_SERVICE_PUBLICURL: t.url ?? '',
      VIKUNJA_SERVICE_TIMEZONE: t.timezone,
      VIKUNJA_SERVICE_ENABLEREGISTRATION: 'true',
    }),
  },
  {
    ...defaults,
    id: 'planka',
    name: 'Planka',
    category: 'productivity',
    website: 'https://planka.app',
    image: 'ghcr.io/plankanban/planka:2',
    port: 1337,
    volumes: [
      { name: 'favicons', mountPath: '/app/public/favicons' },
      { name: 'avatars', mountPath: '/app/public/user-avatars' },
      { name: 'backgrounds', mountPath: '/app/public/background-images' },
      { name: 'attachments', mountPath: '/app/private/attachments' },
    ],
    services: [postgres()],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'login', user: { key: 'DEFAULT_ADMIN_EMAIL' }, passwordKey: 'DEFAULT_ADMIN_PASSWORD' },
    env: (t) => ({
      BASE_URL: t.url ?? '',
      DATABASE_URL: pg.url,
      SECRET_KEY: t.secret(64),
      DEFAULT_ADMIN_EMAIL: t.email,
      DEFAULT_ADMIN_PASSWORD: t.secret(16),
      DEFAULT_ADMIN_NAME: 'Admin',
      DEFAULT_ADMIN_USERNAME: 'admin',
    }),
  },
  {
    ...defaults,
    id: 'kanboard',
    name: 'Kanboard',
    category: 'productivity',
    website: 'https://kanboard.org',
    image: 'kanboard/kanboard:latest',
    port: 80,
    volumes: [
      { name: 'data', mountPath: '/var/www/app/data' },
      { name: 'plugins', mountPath: '/var/www/app/plugins' },
    ],
    services: [postgres()],
    memoryMb: 128,
    access: { kind: 'default', user: 'admin', password: 'admin' },
    env: () => ({ DATABASE_URL: pg.url }),
  },
  {
    ...defaults,
    id: 'wekan',
    name: 'WeKan',
    category: 'productivity',
    website: 'https://wekan.github.io',
    image: 'wekanteam/wekan:latest',
    port: 8080,
    services: [mongo('7.0')],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'setup' },
    env: (t) => ({ MONGO_URL: mongoUrl, ROOT_URL: t.url ?? '', WITH_API: 'true' }),
  },
  {
    ...defaults,
    id: 'leantime',
    name: 'Leantime',
    category: 'productivity',
    website: 'https://leantime.io',
    image: 'leantime/leantime:latest',
    port: 80,
    volumes: [
      { name: 'userfiles', mountPath: '/var/www/html/userfiles' },
      { name: 'public', mountPath: '/var/www/html/public/userfiles' },
    ],
    services: [mysql()],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'setup', path: '/install' },
    env: (t) => ({
      LEAN_DB_HOST: my.host,
      LEAN_DB_PORT: my.port,
      LEAN_DB_USER: my.user,
      LEAN_DB_PASSWORD: my.password,
      LEAN_DB_DATABASE: my.database,
      LEAN_SESSION_PASSWORD: t.secret(32),
      LEAN_APP_URL: t.url ?? '',
      LEAN_DEFAULT_TIMEZONE: t.timezone,
    }),
  },
  {
    ...defaults,
    id: 'openproject',
    name: 'OpenProject',
    category: 'productivity',
    website: 'https://www.openproject.org',
    image: 'openproject/openproject:16',
    port: 80,
    volumes: [{ name: 'assets', mountPath: '/var/openproject/assets' }],
    services: [postgres()],
    needsUrl: true,
    healthCheckPath: '/health_checks/default',
    healthCheckTimeoutSec: 900,
    memoryMb: 2048,
    access: { kind: 'default', user: 'admin', password: 'admin' },
    env: (t) => ({
      DATABASE_URL: pg.url,
      OPENPROJECT_HOST__NAME: t.host ?? '',
      OPENPROJECT_HTTPS: String(t.https),
      OPENPROJECT_SECRET_KEY_BASE: t.secret(64),
      OPENPROJECT_DEFAULT__LANGUAGE: 'en',
    }),
  },
  {
    ...defaults,
    id: 'redmine',
    name: 'Redmine',
    category: 'productivity',
    website: 'https://www.redmine.org',
    image: 'redmine:6',
    port: 3000,
    volumes: [{ name: 'files', mountPath: '/usr/src/redmine/files' }],
    services: [postgres()],
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'default', user: 'admin', password: 'admin' },
    env: (t) => ({
      REDMINE_DB_POSTGRES: pg.host,
      REDMINE_DB_PORT: pg.port,
      REDMINE_DB_USERNAME: pg.user,
      REDMINE_DB_PASSWORD: pg.password,
      REDMINE_DB_DATABASE: pg.database,
      REDMINE_SECRET_KEY_BASE: t.secret(64),
    }),
  },
  {
    ...defaults,
    id: 'memos',
    name: 'Memos',
    category: 'productivity',
    website: 'https://usememos.com',
    image: 'neosmemo/memos:stable',
    port: 5230,
    volumes: [{ name: 'data', mountPath: '/var/opt/memos' }],
    healthCheckPath: '/healthz',
    memoryMb: 128,
    access: { kind: 'setup' },
    env: () => ({}),
  },
  {
    ...defaults,
    id: 'trilium',
    name: 'Trilium Notes',
    category: 'productivity',
    website: 'https://github.com/TriliumNext/Trilium',
    image: 'triliumnext/trilium:latest',
    port: 8080,
    volumes: [{ name: 'data', mountPath: '/home/node/trilium-data' }],
    memoryMb: 256,
    access: { kind: 'setup' },
    env: (t) => ({ TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'joplin',
    name: 'Joplin Server',
    category: 'productivity',
    website: 'https://joplinapp.org',
    image: 'joplin/server:latest',
    port: 22300,
    services: [postgres()],
    needsUrl: true,
    healthCheckPath: '/api/ping',
    memoryMb: 256,
    access: { kind: 'default', user: 'admin@localhost', password: 'admin' },
    env: (t) => ({
      APP_BASE_URL: t.url ?? '',
      APP_PORT: '22300',
      DB_CLIENT: 'pg',
      POSTGRES_HOST: pg.host,
      POSTGRES_PORT: pg.port,
      POSTGRES_DATABASE: pg.database,
      POSTGRES_USER: pg.user,
      POSTGRES_PASSWORD: pg.password,
    }),
  },
  {
    ...defaults,
    id: 'hedgedoc',
    name: 'HedgeDoc',
    category: 'productivity',
    website: 'https://hedgedoc.org',
    image: 'quay.io/hedgedoc/hedgedoc:1',
    port: 3000,
    volumes: [{ name: 'uploads', mountPath: '/hedgedoc/public/uploads' }],
    services: [postgres()],
    needsUrl: true,
    healthCheckPath: '/status',
    memoryMb: 256,
    access: { kind: 'setup' },
    env: (t) => ({
      CMD_DB_URL: pg.url,
      CMD_DOMAIN: t.host ?? '',
      CMD_PROTOCOL_USESSL: String(t.https),
      CMD_URL_ADDPORT: 'false',
      CMD_SESSION_SECRET: t.secret(32),
      CMD_ALLOW_EMAIL_REGISTER: 'true',
    }),
  },
  {
    ...defaults,
    id: 'etherpad',
    name: 'Etherpad',
    category: 'productivity',
    website: 'https://etherpad.org',
    image: 'etherpad/etherpad:latest',
    port: 9001,
    volumes: [{ name: 'data', mountPath: '/opt/etherpad-lite/var' }],
    services: [postgres()],
    healthCheckPath: '/api',
    memoryMb: 256,
    access: { kind: 'login', user: 'admin', passwordKey: 'ADMIN_PASSWORD', path: '/admin' },
    env: (t) => ({
      DB_TYPE: 'postgres',
      DB_HOST: pg.host,
      DB_PORT: pg.port,
      DB_NAME: pg.database,
      DB_USER: pg.user,
      DB_PASS: pg.password,
      ADMIN_PASSWORD: t.secret(16),
      TRUST_PROXY: 'true',
    }),
  },
  {
    ...defaults,
    id: 'flatnotes',
    name: 'flatnotes',
    category: 'productivity',
    website: 'https://github.com/dullage/flatnotes',
    image: 'dullage/flatnotes:latest',
    port: 8080,
    volumes: [{ name: 'data', mountPath: '/data' }],
    memoryMb: 64,
    access: { kind: 'login', user: 'admin', passwordKey: 'FLATNOTES_PASSWORD' },
    env: (t) => ({
      PUID: '1000',
      PGID: '1000',
      FLATNOTES_AUTH_TYPE: 'password',
      FLATNOTES_USERNAME: 'admin',
      FLATNOTES_PASSWORD: t.secret(16),
      FLATNOTES_SECRET_KEY: t.secret(32),
    }),
  },
  {
    ...defaults,
    id: 'linkding',
    name: 'linkding',
    category: 'productivity',
    website: 'https://linkding.link',
    image: 'sissbruecker/linkding:latest',
    port: 9090,
    volumes: [{ name: 'data', mountPath: '/etc/linkding/data' }],
    healthCheckPath: '/health',
    memoryMb: 128,
    access: { kind: 'login', user: 'admin', passwordKey: 'LD_SUPERUSER_PASSWORD' },
    env: (t) => ({ LD_SUPERUSER_NAME: 'admin', LD_SUPERUSER_PASSWORD: t.secret(16) }),
  },
  {
    ...defaults,
    id: 'linkwarden',
    name: 'Linkwarden',
    category: 'productivity',
    website: 'https://linkwarden.app',
    image: 'ghcr.io/linkwarden/linkwarden:latest',
    port: 3000,
    volumes: [{ name: 'data', mountPath: '/data/data' }],
    services: [postgres()],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 1024,
    access: { kind: 'setup' },
    env: (t) => ({ DATABASE_URL: pg.url, NEXTAUTH_SECRET: t.secret(32), NEXTAUTH_URL: `${t.url}/api/v1/auth`, NEXT_PUBLIC_DISABLE_REGISTRATION: 'false' }),
  },
  {
    ...defaults,
    id: 'readeck',
    name: 'Readeck',
    category: 'productivity',
    website: 'https://readeck.org',
    image: 'codeberg.org/readeck/readeck:latest',
    port: 8000,
    volumes: [{ name: 'data', mountPath: '/readeck' }],
    memoryMb: 128,
    access: { kind: 'setup' },
    env: (t) => ({ READECK_SERVER_HOST: '0.0.0.0', READECK_SERVER_PORT: '8000', READECK_ALLOWED_HOSTS: t.host ?? '' }),
  },
  {
    ...defaults,
    id: 'wallabag',
    name: 'wallabag',
    category: 'productivity',
    website: 'https://wallabag.org',
    image: 'wallabag/wallabag:latest',
    port: 80,
    volumes: [
      { name: 'data', mountPath: '/var/www/wallabag/data' },
      { name: 'images', mountPath: '/var/www/wallabag/web/assets/images' },
    ],
    services: [mariadb()],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 256,
    access: { kind: 'default', user: 'wallabag', password: 'wallabag' },
    env: (t) => ({
      SYMFONY__ENV__DATABASE_DRIVER: 'pdo_mysql',
      SYMFONY__ENV__DATABASE_HOST: my.host,
      SYMFONY__ENV__DATABASE_PORT: my.port,
      SYMFONY__ENV__DATABASE_NAME: my.database,
      SYMFONY__ENV__DATABASE_USER: my.user,
      SYMFONY__ENV__DATABASE_PASSWORD: my.password,
      SYMFONY__ENV__DATABASE_CHARSET: 'utf8mb4',
      SYMFONY__ENV__DOMAIN_NAME: t.url ?? '',
      SYMFONY__ENV__SECRET: t.secret(32),
      SYMFONY__ENV__FOSUSER_REGISTRATION: 'false',
    }),
  },
  {
    ...defaults,
    id: 'freshrss',
    name: 'FreshRSS',
    category: 'productivity',
    website: 'https://freshrss.org',
    image: 'freshrss/freshrss:latest',
    port: 80,
    volumes: [
      { name: 'data', mountPath: '/var/www/FreshRSS/data' },
      { name: 'extensions', mountPath: '/var/www/FreshRSS/extensions' },
    ],
    memoryMb: 128,
    access: { kind: 'setup' },
    env: (t) => ({ TZ: t.timezone, CRON_MIN: '*/20' }),
  },
  {
    ...defaults,
    id: 'miniflux',
    name: 'Miniflux',
    category: 'productivity',
    website: 'https://miniflux.app',
    image: 'miniflux/miniflux:latest',
    port: 8080,
    services: [postgres()],
    healthCheckPath: '/healthcheck',
    memoryMb: 128,
    access: { kind: 'login', user: 'admin', passwordKey: 'ADMIN_PASSWORD' },
    env: (t) => ({
      DATABASE_URL: `${pg.url}?sslmode=disable`,
      RUN_MIGRATIONS: '1',
      CREATE_ADMIN: '1',
      ADMIN_USERNAME: 'admin',
      ADMIN_PASSWORD: t.secret(16),
      ...urlEnv(t, 'BASE_URL'),
    }),
  },
  {
    ...defaults,
    id: 'mealie',
    name: 'Mealie',
    category: 'productivity',
    website: 'https://mealie.io',
    image: 'ghcr.io/mealie-recipes/mealie:latest',
    port: 9000,
    volumes: [{ name: 'data', mountPath: '/app/data' }],
    services: [postgres()],
    healthCheckPath: '/api/app/about',
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'default', user: 'changeme@example.com', password: 'MyPassword' },
    env: (t) => ({
      DB_ENGINE: 'postgres',
      POSTGRES_SERVER: pg.host,
      POSTGRES_PORT: pg.port,
      POSTGRES_DB: pg.database,
      POSTGRES_USER: pg.user,
      POSTGRES_PASSWORD: pg.password,
      ...urlEnv(t, 'BASE_URL'),
      ALLOW_SIGNUP: 'false',
      TZ: t.timezone,
    }),
  },
  {
    ...defaults,
    id: 'tandoor',
    name: 'Tandoor Recipes',
    category: 'productivity',
    website: 'https://tandoor.dev',
    image: 'vabene1111/recipes:latest',
    port: 8080,
    volumes: [
      { name: 'static', mountPath: '/opt/recipes/staticfiles' },
      { name: 'media', mountPath: '/opt/recipes/mediafiles' },
    ],
    services: [postgres()],
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'setup' },
    env: (t) => ({
      DB_ENGINE: 'django.db.backends.postgresql',
      POSTGRES_HOST: pg.host,
      POSTGRES_PORT: pg.port,
      POSTGRES_DB: pg.database,
      POSTGRES_USER: pg.user,
      POSTGRES_PASSWORD: pg.password,
      SECRET_KEY: t.secret(48),
      ALLOWED_HOSTS: '*',
      GUNICORN_MEDIA: '1',
      TZ: t.timezone,
    }),
  },
  {
    ...defaults,
    id: 'baikal',
    name: 'Baïkal',
    category: 'productivity',
    website: 'https://sabre.io/baikal',
    image: 'ckulka/baikal:nginx',
    port: 80,
    volumes: [
      { name: 'config', mountPath: '/var/www/baikal/config' },
      { name: 'specific', mountPath: '/var/www/baikal/Specific' },
    ],
    memoryMb: 64,
    access: { kind: 'setup', path: '/admin/' },
    env: () => ({}),
  },

  // ================================================================= business
  {
    ...defaults,
    id: 'actual',
    name: 'Actual Budget',
    category: 'business',
    website: 'https://actualbudget.org',
    image: 'actualbudget/actual-server:latest',
    port: 5006,
    volumes: [{ name: 'data', mountPath: '/data' }],
    memoryMb: 128,
    access: { kind: 'setup' },
    env: () => ({}),
  },
  {
    ...defaults,
    id: 'firefly',
    name: 'Firefly III',
    category: 'business',
    website: 'https://www.firefly-iii.org',
    image: 'fireflyiii/core:latest',
    port: 8080,
    volumes: [{ name: 'upload', mountPath: '/var/www/html/storage/upload' }],
    services: [postgres()],
    needsUrl: true,
    healthCheckPath: '/health',
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'setup' },
    env: (t) => ({
      DB_CONNECTION: 'pgsql',
      DB_HOST: pg.host,
      DB_PORT: pg.port,
      DB_DATABASE: pg.database,
      DB_USERNAME: pg.user,
      DB_PASSWORD: pg.password,
      // Firefly wants exactly 32 characters here.
      APP_KEY: t.secret(32),
      APP_URL: t.url ?? '',
      TRUSTED_PROXIES: '**',
      SITE_OWNER: t.email,
      TZ: t.timezone,
    }),
  },
  {
    ...defaults,
    id: 'wallos',
    name: 'Wallos',
    category: 'business',
    website: 'https://wallosapp.com',
    image: 'bellamy/wallos:latest',
    port: 80,
    volumes: [
      { name: 'db', mountPath: '/var/www/html/db' },
      { name: 'logos', mountPath: '/var/www/html/images/uploads/logos' },
    ],
    memoryMb: 64,
    access: { kind: 'setup' },
    env: (t) => ({ TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'ghostfolio',
    name: 'Ghostfolio',
    category: 'business',
    website: 'https://ghostfol.io',
    image: 'ghostfolio/ghostfolio:latest',
    port: 3333,
    services: [postgres(), redis()],
    healthCheckPath: '/api/v1/health',
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'setup' },
    env: (t) => ({
      DATABASE_URL: `${pg.url}?connect_timeout=300&sslmode=prefer`,
      REDIS_HOST: cache.host,
      REDIS_PORT: cache.port,
      REDIS_PASSWORD: cache.password,
      ACCESS_TOKEN_SALT: t.secret(32),
      JWT_SECRET_KEY: t.secret(32),
      NODE_ENV: 'production',
    }),
  },
  {
    ...defaults,
    id: 'kimai',
    name: 'Kimai',
    category: 'business',
    website: 'https://www.kimai.org',
    image: 'kimai/kimai2:apache',
    port: 8001,
    volumes: [
      { name: 'data', mountPath: '/opt/kimai/var/data' },
      { name: 'plugins', mountPath: '/opt/kimai/var/plugins' },
    ],
    services: [mysql()],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'login', user: { key: 'ADMINMAIL' }, passwordKey: 'ADMINPASS' },
    env: (t) => ({
      DATABASE_URL: `${my.url}?charset=utf8mb4&serverVersion=8.4.0`,
      ADMINMAIL: t.email,
      ADMINPASS: t.secret(16),
      TRUSTED_HOSTS: t.host ?? 'localhost',
      TRUSTED_PROXIES: '10.0.0.0/8,172.16.0.0/12,192.168.0.0/16',
    }),
  },
  {
    ...defaults,
    id: 'dolibarr',
    name: 'Dolibarr',
    category: 'business',
    website: 'https://www.dolibarr.org',
    image: 'dolibarr/dolibarr:21',
    port: 80,
    volumes: [
      { name: 'documents', mountPath: '/var/www/documents' },
      { name: 'custom', mountPath: '/var/www/html/custom' },
    ],
    services: [mariadb()],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'login', user: 'admin', passwordKey: 'DOLI_ADMIN_PASSWORD' },
    env: (t) => ({
      DOLI_DB_HOST: my.host,
      DOLI_DB_HOST_PORT: my.port,
      DOLI_DB_NAME: my.database,
      DOLI_DB_USER: my.user,
      DOLI_DB_PASSWORD: my.password,
      DOLI_URL_ROOT: t.url ?? '',
      DOLI_ADMIN_LOGIN: 'admin',
      DOLI_ADMIN_PASSWORD: t.secret(16),
      DOLI_INSTALL_AUTO: '1',
      DOLI_INIT_DEMO: '0',
    }),
  },
  {
    ...defaults,
    id: 'odoo',
    name: 'Odoo',
    category: 'business',
    website: 'https://www.odoo.com',
    image: 'odoo:18',
    port: 8069,
    volumes: [{ name: 'data', mountPath: '/var/lib/odoo' }],
    services: [postgres()],
    healthCheckPath: '/web/health',
    healthCheckTimeoutSec: 600,
    memoryMb: 2048,
    // The first visit shows Odoo's database manager: create a database there (the user is a superuser).
    access: { kind: 'setup', path: '/web/database/manager' },
    env: () => ({ HOST: pg.host, PORT: pg.port, USER: pg.user, PASSWORD: pg.password }),
  },
  {
    ...defaults,
    id: 'espocrm',
    name: 'EspoCRM',
    category: 'business',
    website: 'https://www.espocrm.com',
    image: 'espocrm/espocrm:latest',
    port: 80,
    volumes: [{ name: 'html', mountPath: '/var/www/html' }],
    services: [mariadb()],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'login', user: 'admin', passwordKey: 'ESPOCRM_ADMIN_PASSWORD' },
    env: (t) => ({
      ESPOCRM_DATABASE_PLATFORM: 'Mysql',
      ESPOCRM_DATABASE_HOST: my.host,
      ESPOCRM_DATABASE_PORT: my.port,
      ESPOCRM_DATABASE_NAME: my.database,
      ESPOCRM_DATABASE_USER: my.user,
      ESPOCRM_DATABASE_PASSWORD: my.password,
      ESPOCRM_ADMIN_USERNAME: 'admin',
      ESPOCRM_ADMIN_PASSWORD: t.secret(16),
      ESPOCRM_SITE_URL: t.url ?? '',
    }),
  },
  {
    ...defaults,
    id: 'twenty',
    name: 'Twenty CRM',
    category: 'business',
    website: 'https://twenty.com',
    image: 'twentycrm/twenty:latest',
    port: 3000,
    volumes: [{ name: 'storage', mountPath: '/app/packages/twenty-server/.local-storage' }],
    services: [postgres(), redis()],
    needsUrl: true,
    healthCheckPath: '/healthz',
    healthCheckTimeoutSec: 600,
    memoryMb: 1024,
    access: { kind: 'setup' },
    env: (t) => ({
      SERVER_URL: t.url ?? '',
      PG_DATABASE_URL: pg.url,
      REDIS_URL: cache.url,
      APP_SECRET: t.base64(32),
      STORAGE_TYPE: 'local',
      SIGN_IN_PREFILLED: 'false',
    }),
  },
  {
    ...defaults,
    id: 'monica',
    name: 'Monica',
    category: 'business',
    website: 'https://www.monicahq.com',
    image: 'monica:4-apache',
    port: 80,
    volumes: [{ name: 'storage', mountPath: '/var/www/html/storage' }],
    services: [mysql()],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 256,
    access: { kind: 'setup', path: '/register' },
    env: (t) => ({
      APP_ENV: 'production',
      APP_KEY: t.secret(32),
      APP_URL: t.url ?? '',
      APP_TRUSTED_PROXIES: '*',
      DB_HOST: my.host,
      DB_PORT: my.port,
      DB_DATABASE: my.database,
      DB_USERNAME: my.user,
      DB_PASSWORD: my.password,
    }),
  },
  {
    ...defaults,
    id: 'snipe-it',
    name: 'Snipe-IT',
    category: 'business',
    website: 'https://snipeitapp.com',
    image: 'snipe/snipe-it:latest',
    port: 80,
    volumes: [{ name: 'data', mountPath: '/var/lib/snipeit' }],
    services: [mysql()],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'setup', path: '/setup' },
    env: (t) => ({
      APP_KEY: laravelKey(t),
      APP_URL: t.url ?? '',
      APP_TRUSTED_PROXIES: '*',
      APP_TIMEZONE: t.timezone,
      MYSQL_PORT_3306_TCP_ADDR: my.host,
      MYSQL_PORT_3306_TCP_PORT: my.port,
      MYSQL_DATABASE: my.database,
      MYSQL_USER: my.user,
      MYSQL_PASSWORD: my.password,
    }),
  },
  {
    ...defaults,
    id: 'limesurvey',
    name: 'LimeSurvey',
    category: 'business',
    website: 'https://www.limesurvey.org',
    image: 'martialblog/limesurvey:6-apache',
    port: 8080,
    volumes: [{ name: 'upload', mountPath: '/var/www/html/upload' }],
    services: [mariadb()],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 256,
    access: { kind: 'login', user: 'admin', passwordKey: 'ADMIN_PASSWORD', path: '/admin' },
    env: (t) => ({
      DB_TYPE: 'mysql',
      DB_HOST: my.host,
      DB_PORT: my.port,
      DB_NAME: my.database,
      DB_USERNAME: my.user,
      DB_PASSWORD: my.password,
      ADMIN_USER: 'admin',
      ADMIN_PASSWORD: t.secret(16),
      ADMIN_NAME: 'Administrator',
      ADMIN_EMAIL: t.email,
      PUBLIC_URL: t.url ?? '',
    }),
  },
  {
    ...defaults,
    id: 'freescout',
    name: 'FreeScout',
    category: 'business',
    website: 'https://freescout.net',
    image: 'tiredofit/freescout:latest',
    port: 80,
    volumes: [
      { name: 'data', mountPath: '/data' },
      { name: 'html', mountPath: '/www/html' },
    ],
    services: [mariadb()],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'login', user: { key: 'ADMIN_EMAIL' }, passwordKey: 'ADMIN_PASS' },
    env: (t) => ({
      DB_HOST: my.host,
      DB_PORT: my.port,
      DB_NAME: my.database,
      DB_USER: my.user,
      DB_PASS: my.password,
      SITE_URL: t.url ?? '',
      ADMIN_EMAIL: t.email,
      ADMIN_PASS: t.secret(16),
      ENABLE_SSL_PROXY: String(t.https).toUpperCase(),
      DISPLAY_ERRORS: 'FALSE',
      TIMEZONE: t.timezone,
    }),
  },
  {
    ...defaults,
    id: 'docuseal',
    name: 'DocuSeal',
    category: 'business',
    website: 'https://www.docuseal.com',
    image: 'docuseal/docuseal:latest',
    port: 3000,
    volumes: [{ name: 'data', mountPath: '/data/docuseal' }],
    services: [postgres()],
    healthCheckPath: '/up',
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'setup' },
    env: (t) => ({ DATABASE_URL: pg.url, SECRET_KEY_BASE: t.secret(64), ...urlEnv(t, 'HOST') }),
  },

  // ============================================================ communication
  {
    ...defaults,
    id: 'mattermost',
    name: 'Mattermost',
    category: 'communication',
    website: 'https://mattermost.com',
    image: 'mattermost/mattermost-team-edition:10',
    port: 8065,
    volumes: [
      { name: 'config', mountPath: '/mattermost/config' },
      { name: 'data', mountPath: '/mattermost/data' },
      { name: 'logs', mountPath: '/mattermost/logs' },
      { name: 'plugins', mountPath: '/mattermost/plugins' },
      { name: 'client-plugins', mountPath: '/mattermost/client/plugins' },
      { name: 'bleve', mountPath: '/mattermost/bleve-indexes' },
    ],
    services: [postgres()],
    needsUrl: true,
    healthCheckPath: '/api/v4/system/ping',
    healthCheckTimeoutSec: 300,
    memoryMb: 1024,
    access: { kind: 'setup' },
    featured: true,
    env: (t) => ({
      MM_SQLSETTINGS_DRIVERNAME: 'postgres',
      MM_SQLSETTINGS_DATASOURCE: `${pg.url}?sslmode=disable&connect_timeout=10`,
      MM_SERVICESETTINGS_SITEURL: t.url ?? '',
      TZ: t.timezone,
    }),
  },
  {
    ...defaults,
    id: 'listmonk',
    name: 'listmonk',
    category: 'communication',
    website: 'https://listmonk.app',
    image: 'listmonk/listmonk:latest',
    port: 9000,
    volumes: [{ name: 'uploads', mountPath: '/listmonk/uploads' }],
    services: [postgres()],
    needsUrl: true,
    healthCheckPath: '/health',
    memoryMb: 128,
    access: { kind: 'login', user: 'admin', passwordKey: 'LISTMONK_ADMIN_PASSWORD', path: '/admin' },
    env: (t) => ({
      LISTMONK_app__address: '0.0.0.0:9000',
      LISTMONK_app__root_url: t.url ?? '',
      LISTMONK_db__host: pg.host,
      LISTMONK_db__port: pg.port,
      LISTMONK_db__user: pg.user,
      LISTMONK_db__password: pg.password,
      LISTMONK_db__database: pg.database,
      LISTMONK_db__ssl_mode: 'disable',
      LISTMONK_ADMIN_USER: 'admin',
      LISTMONK_ADMIN_PASSWORD: t.secret(16),
      TZ: t.timezone,
    }),
  },
  {
    ...defaults,
    id: 'mautic',
    name: 'Mautic',
    category: 'communication',
    website: 'https://www.mautic.org',
    image: 'mautic/mautic:5-apache',
    port: 80,
    volumes: [
      { name: 'config', mountPath: '/var/www/html/config' },
      { name: 'logs', mountPath: '/var/www/html/var/logs' },
      { name: 'files', mountPath: '/var/www/html/docroot/media/files' },
      { name: 'images', mountPath: '/var/www/html/docroot/media/images' },
    ],
    services: [mysql()],
    needsUrl: true,
    healthCheckTimeoutSec: 600,
    memoryMb: 1024,
    access: { kind: 'setup', path: '/installer' },
    env: () => ({
      MAUTIC_DB_HOST: my.host,
      MAUTIC_DB_PORT: my.port,
      MAUTIC_DB_DATABASE: my.database,
      MAUTIC_DB_USER: my.user,
      MAUTIC_DB_PASSWORD: my.password,
      MAUTIC_RUN_MIGRATIONS: 'true',
      DOCKER_MAUTIC_ROLE: 'mautic_web',
    }),
  },
  {
    ...defaults,
    id: 'ntfy',
    name: 'ntfy',
    category: 'communication',
    website: 'https://ntfy.sh',
    image: 'binwiederhier/ntfy:latest',
    port: 80,
    volumes: [{ name: 'cache', mountPath: '/var/cache/ntfy' }],
    needsUrl: true,
    healthCheckPath: '/v1/health',
    memoryMb: 64,
    access: { kind: 'open' },
    // The image's entrypoint is the binary itself; `serve` is the subcommand.
    command: 'ntfy serve',
    env: (t) => ({
      NTFY_BASE_URL: t.url ?? '',
      NTFY_LISTEN_HTTP: ':80',
      NTFY_CACHE_FILE: '/var/cache/ntfy/cache.db',
      NTFY_ATTACHMENT_CACHE_DIR: '/var/cache/ntfy/attachments',
      NTFY_BEHIND_PROXY: 'true',
      TZ: t.timezone,
    }),
  },
  {
    ...defaults,
    id: 'gotify',
    name: 'Gotify',
    category: 'communication',
    website: 'https://gotify.net',
    image: 'gotify/server:latest',
    port: 80,
    volumes: [{ name: 'data', mountPath: '/app/data' }],
    healthCheckPath: '/health',
    memoryMb: 64,
    access: { kind: 'login', user: 'admin', passwordKey: 'GOTIFY_DEFAULTUSER_PASS' },
    env: (t) => ({ GOTIFY_DEFAULTUSER_NAME: 'admin', GOTIFY_DEFAULTUSER_PASS: t.secret(16), TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'apprise',
    name: 'Apprise API',
    category: 'communication',
    website: 'https://github.com/caronc/apprise-api',
    image: 'caronc/apprise:latest',
    port: 8000,
    volumes: [{ name: 'config', mountPath: '/config' }],
    memoryMb: 128,
    access: { kind: 'open' },
    env: (t) => ({ TZ: t.timezone }),
  },

  // ================================================================ developer
  {
    ...defaults,
    id: 'gitea',
    name: 'Gitea',
    category: 'developer',
    website: 'https://about.gitea.com',
    image: 'gitea/gitea:latest',
    port: 3000,
    volumes: [{ name: 'data', mountPath: '/data' }],
    services: [postgres()],
    needsUrl: true,
    healthCheckPath: '/api/healthz',
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'setup' },
    featured: true,
    env: (t) => ({
      USER_UID: '1000',
      USER_GID: '1000',
      GITEA__database__DB_TYPE: 'postgres',
      GITEA__database__HOST: pg.hostPort,
      GITEA__database__NAME: pg.database,
      GITEA__database__USER: pg.user,
      GITEA__database__PASSWD: pg.password,
      GITEA__server__DOMAIN: t.host ?? '',
      GITEA__server__ROOT_URL: `${t.url}/`,
      // Only HTTP(S) is routed to apps; Git over SSH would need a published port.
      GITEA__server__DISABLE_SSH: 'true',
    }),
  },
  {
    ...defaults,
    id: 'forgejo',
    name: 'Forgejo',
    category: 'developer',
    website: 'https://forgejo.org',
    image: 'codeberg.org/forgejo/forgejo:11',
    port: 3000,
    volumes: [{ name: 'data', mountPath: '/data' }],
    services: [postgres()],
    needsUrl: true,
    healthCheckPath: '/api/healthz',
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'setup' },
    env: (t) => ({
      USER_UID: '1000',
      USER_GID: '1000',
      FORGEJO__database__DB_TYPE: 'postgres',
      FORGEJO__database__HOST: pg.hostPort,
      FORGEJO__database__NAME: pg.database,
      FORGEJO__database__USER: pg.user,
      FORGEJO__database__PASSWD: pg.password,
      FORGEJO__server__DOMAIN: t.host ?? '',
      FORGEJO__server__ROOT_URL: `${t.url}/`,
      FORGEJO__server__DISABLE_SSH: 'true',
    }),
  },
  {
    ...defaults,
    id: 'gitlab',
    name: 'GitLab CE',
    category: 'developer',
    website: 'https://about.gitlab.com',
    image: 'gitlab/gitlab-ce:latest',
    port: 80,
    volumes: [
      { name: 'config', mountPath: '/etc/gitlab' },
      { name: 'logs', mountPath: '/var/log/gitlab' },
      { name: 'data', mountPath: '/var/opt/gitlab' },
    ],
    needsUrl: true,
    healthCheckPath: '/-/health',
    healthCheckTimeoutSec: 1200,
    memoryMb: 4096,
    access: { kind: 'login', user: 'root', passwordKey: 'GITLAB_ROOT_PASSWORD' },
    env: (t) => ({
      GITLAB_OMNIBUS_CONFIG: [
        `external_url '${t.url}'`,
        "nginx['listen_port'] = 80",
        "nginx['listen_https'] = false",
        "letsencrypt['enable'] = false",
        "gitlab_rails['gitlab_shell_ssh_port'] = 22",
        "puma['worker_processes'] = 2",
        "sidekiq['concurrency'] = 10",
        "prometheus_monitoring['enable'] = false",
      ].join('; '),
      GITLAB_ROOT_PASSWORD: t.secret(20),
      GITLAB_ROOT_EMAIL: t.email,
    }),
  },
  {
    ...defaults,
    id: 'jenkins',
    name: 'Jenkins',
    category: 'developer',
    website: 'https://www.jenkins.io',
    image: 'jenkins/jenkins:lts-jdk21',
    port: 8080,
    volumes: [{ name: 'home', mountPath: '/var/jenkins_home' }],
    healthCheckPath: '/login',
    healthCheckTimeoutSec: 300,
    memoryMb: 1024,
    // The unlock password is printed in the log (and in /var/jenkins_home/secrets/initialAdminPassword).
    access: { kind: 'logs' },
    env: (t) => ({ TZ: t.timezone, JAVA_OPTS: `-Duser.timezone=${t.timezone}` }),
  },
  {
    ...defaults,
    id: 'onedev',
    name: 'OneDev',
    category: 'developer',
    website: 'https://onedev.io',
    image: '1dev/server:latest',
    port: 6610,
    volumes: [{ name: 'data', mountPath: '/opt/onedev' }],
    healthCheckTimeoutSec: 600,
    memoryMb: 2048,
    access: { kind: 'setup' },
    env: (t) => ({ TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'semaphore',
    name: 'Semaphore UI',
    category: 'developer',
    website: 'https://semaphoreui.com',
    image: 'semaphoreui/semaphore:latest',
    port: 3000,
    volumes: [
      { name: 'data', mountPath: '/var/lib/semaphore' },
      { name: 'config', mountPath: '/etc/semaphore' },
    ],
    services: [postgres()],
    healthCheckPath: '/api/ping',
    memoryMb: 256,
    access: { kind: 'login', user: 'admin', passwordKey: 'SEMAPHORE_ADMIN_PASSWORD' },
    env: (t) => ({
      SEMAPHORE_DB_DIALECT: 'postgres',
      SEMAPHORE_DB_HOST: pg.host,
      SEMAPHORE_DB_PORT: pg.port,
      SEMAPHORE_DB_USER: pg.user,
      SEMAPHORE_DB_PASS: pg.password,
      SEMAPHORE_DB_NAME: pg.database,
      SEMAPHORE_ADMIN: 'admin',
      SEMAPHORE_ADMIN_PASSWORD: t.secret(16),
      SEMAPHORE_ADMIN_NAME: 'Admin',
      SEMAPHORE_ADMIN_EMAIL: t.email,
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: t.base64(32),
      ...urlEnv(t, 'SEMAPHORE_WEB_ROOT'),
      TZ: t.timezone,
    }),
  },
  {
    ...defaults,
    id: 'code-server',
    name: 'code-server',
    category: 'developer',
    website: 'https://coder.com/docs/code-server',
    image: 'codercom/code-server:latest',
    port: 8080,
    volumes: [{ name: 'home', mountPath: '/home/coder' }],
    healthCheckPath: '/healthz',
    memoryMb: 512,
    access: { kind: 'password', key: 'PASSWORD' },
    env: (t) => ({ PASSWORD: t.secret(16), SUDO_PASSWORD: t.secret(16), TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'verdaccio',
    name: 'Verdaccio',
    category: 'developer',
    website: 'https://verdaccio.org',
    image: 'verdaccio/verdaccio:6',
    port: 4873,
    volumes: [{ name: 'storage', mountPath: '/verdaccio/storage' }],
    healthCheckPath: '/-/ping',
    memoryMb: 128,
    // Accounts are made with `npm adduser --registry <url>`.
    access: { kind: 'open' },
    env: () => ({}),
  },
  {
    ...defaults,
    id: 'mailpit',
    name: 'Mailpit',
    category: 'developer',
    website: 'https://mailpit.axllent.org',
    image: 'axllent/mailpit:latest',
    port: 8025,
    volumes: [{ name: 'data', mountPath: '/data' }],
    memoryMb: 64,
    access: { kind: 'login', user: 'admin', passwordKey: 'MAILPIT_PASSWORD' },
    env: (t) => {
      const password = t.secret(20);
      return {
        MAILPIT_PASSWORD: password,
        // The web UI is public through the proxy, so it gets basic auth; SMTP (1025) stays on the project network.
        MP_UI_AUTH: 'admin:${MAILPIT_PASSWORD}',
        MP_DATABASE: '/data/mailpit.db',
        MP_SMTP_AUTH_ACCEPT_ANY: '1',
        MP_SMTP_AUTH_ALLOW_INSECURE: '1',
      };
    },
  },
  {
    ...defaults,
    id: 'gotenberg',
    name: 'Gotenberg',
    category: 'developer',
    website: 'https://gotenberg.dev',
    image: 'gotenberg/gotenberg:8',
    port: 3000,
    healthCheckPath: '/health',
    memoryMb: 512,
    access: { kind: 'open' },
    env: () => ({}),
  },
  {
    ...defaults,
    id: 'browserless',
    name: 'Browserless',
    category: 'developer',
    website: 'https://www.browserless.io',
    image: 'ghcr.io/browserless/chromium:latest',
    port: 3000,
    memoryMb: 1024,
    access: { kind: 'key', key: 'TOKEN' },
    env: (t) => ({ TOKEN: t.secret(32), TIMEOUT: '60000', CONCURRENT: '5' }),
  },
  {
    ...defaults,
    id: 'bugsink',
    name: 'Bugsink',
    category: 'developer',
    website: 'https://www.bugsink.com',
    image: 'bugsink/bugsink:latest',
    port: 8000,
    volumes: [{ name: 'data', mountPath: '/data' }],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 256,
    access: { kind: 'login', user: 'admin', passwordKey: 'BUGSINK_ADMIN_PASSWORD' },
    env: (t) => ({
      SECRET_KEY: t.secret(50),
      BUGSINK_ADMIN_PASSWORD: t.secret(16),
      CREATE_SUPERUSER: 'admin:${BUGSINK_ADMIN_PASSWORD}',
      PORT: '8000',
      BASE_URL: t.url ?? '',
      BEHIND_HTTPS_PROXY: String(t.https),
      TZ: t.timezone,
    }),
  },
  {
    ...defaults,
    id: 'budibase',
    name: 'Budibase',
    category: 'developer',
    website: 'https://budibase.com',
    image: 'budibase/budibase:latest',
    port: 80,
    volumes: [{ name: 'data', mountPath: '/data' }],
    healthCheckTimeoutSec: 600,
    memoryMb: 2048,
    access: { kind: 'setup' },
    env: () => ({}),
  },
  {
    ...defaults,
    id: 'appsmith',
    name: 'Appsmith',
    category: 'developer',
    website: 'https://www.appsmith.com',
    image: 'appsmith/appsmith-ce:latest',
    port: 80,
    volumes: [{ name: 'stacks', mountPath: '/appsmith-stacks' }],
    healthCheckTimeoutSec: 900,
    memoryMb: 4096,
    access: { kind: 'setup' },
    env: (t) => ({ TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'pocketbase',
    name: 'PocketBase',
    category: 'developer',
    website: 'https://pocketbase.io',
    image: 'ghcr.io/muchobien/pocketbase:latest',
    port: 8090,
    volumes: [{ name: 'data', mountPath: '/pb_data' }],
    healthCheckPath: '/api/health',
    memoryMb: 64,
    access: { kind: 'setup', path: '/_/' },
    env: () => ({}),
  },

  // ================================================================= database
  {
    ...defaults,
    id: 'pgadmin',
    name: 'pgAdmin',
    category: 'database',
    website: 'https://www.pgadmin.org',
    image: 'dpage/pgadmin4:latest',
    port: 5050,
    volumes: [{ name: 'data', mountPath: '/var/lib/pgadmin' }],
    healthCheckPath: '/misc/ping',
    healthCheckTimeoutSec: 300,
    memoryMb: 256,
    access: { kind: 'login', user: { key: 'PGADMIN_DEFAULT_EMAIL' }, passwordKey: 'PGADMIN_DEFAULT_PASSWORD' },
    env: (t) => ({ PGADMIN_DEFAULT_EMAIL: t.email, PGADMIN_DEFAULT_PASSWORD: t.secret(20), PGADMIN_LISTEN_PORT: '5050' }),
  },
  {
    ...defaults,
    id: 'adminer',
    name: 'Adminer',
    category: 'database',
    website: 'https://www.adminer.org',
    image: 'adminer:latest',
    port: 8080,
    memoryMb: 64,
    access: { kind: 'database' },
    env: () => ({}),
  },
  {
    ...defaults,
    id: 'phpmyadmin',
    name: 'phpMyAdmin',
    category: 'database',
    website: 'https://www.phpmyadmin.net',
    image: 'phpmyadmin:5-apache',
    port: 80,
    memoryMb: 128,
    access: { kind: 'database' },
    env: () => ({ PMA_ARBITRARY: '1', UPLOAD_LIMIT: '256M' }),
  },
  {
    ...defaults,
    id: 'cloudbeaver',
    name: 'CloudBeaver',
    category: 'database',
    website: 'https://dbeaver.com/cloudbeaver',
    image: 'dbeaver/cloudbeaver:latest',
    port: 8978,
    volumes: [{ name: 'workspace', mountPath: '/opt/cloudbeaver/workspace' }],
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'setup' },
    env: () => ({}),
  },
  {
    ...defaults,
    id: 'redisinsight',
    name: 'Redis Insight',
    category: 'database',
    website: 'https://redis.io/insight',
    image: 'redis/redisinsight:latest',
    port: 5540,
    volumes: [{ name: 'data', mountPath: '/data' }],
    healthCheckPath: '/api/health',
    memoryMb: 256,
    access: { kind: 'open' },
    env: () => ({}),
  },
  {
    ...defaults,
    id: 'meilisearch',
    name: 'Meilisearch',
    category: 'database',
    website: 'https://www.meilisearch.com',
    image: 'getmeili/meilisearch:latest',
    port: 7700,
    volumes: [{ name: 'data', mountPath: '/meili_data' }],
    healthCheckPath: '/health',
    memoryMb: 512,
    access: { kind: 'key', key: 'MEILI_MASTER_KEY' },
    env: (t) => ({ MEILI_MASTER_KEY: t.secret(32), MEILI_ENV: 'production', MEILI_NO_ANALYTICS: 'true' }),
  },
  {
    ...defaults,
    id: 'typesense',
    name: 'Typesense',
    category: 'database',
    website: 'https://typesense.org',
    image: 'typesense/typesense:29.0',
    port: 8108,
    volumes: [{ name: 'data', mountPath: '/data' }],
    healthCheckPath: '/health',
    memoryMb: 512,
    access: { kind: 'key', key: 'TYPESENSE_API_KEY' },
    env: (t) => ({ TYPESENSE_DATA_DIR: '/data', TYPESENSE_API_KEY: t.secret(32), TYPESENSE_ENABLE_CORS: 'true' }),
  },
  {
    ...defaults,
    id: 'couchdb',
    name: 'CouchDB',
    category: 'database',
    website: 'https://couchdb.apache.org',
    image: 'couchdb:3',
    port: 5984,
    volumes: [{ name: 'data', mountPath: '/opt/couchdb/data' }],
    healthCheckPath: '/_up',
    memoryMb: 512,
    access: { kind: 'login', user: 'admin', passwordKey: 'COUCHDB_PASSWORD', path: '/_utils' },
    env: (t) => ({ COUCHDB_USER: 'admin', COUCHDB_PASSWORD: t.secret(20) }),
  },
  {
    ...defaults,
    id: 'influxdb',
    name: 'InfluxDB',
    category: 'database',
    website: 'https://www.influxdata.com',
    image: 'influxdb:2',
    port: 8086,
    volumes: [
      { name: 'data', mountPath: '/var/lib/influxdb2' },
      { name: 'config', mountPath: '/etc/influxdb2' },
    ],
    healthCheckPath: '/health',
    memoryMb: 512,
    access: { kind: 'login', user: 'admin', passwordKey: 'DOCKER_INFLUXDB_INIT_PASSWORD' },
    env: (t) => ({
      DOCKER_INFLUXDB_INIT_MODE: 'setup',
      DOCKER_INFLUXDB_INIT_USERNAME: 'admin',
      DOCKER_INFLUXDB_INIT_PASSWORD: t.secret(20),
      DOCKER_INFLUXDB_INIT_ORG: 'main',
      DOCKER_INFLUXDB_INIT_BUCKET: 'main',
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: t.secret(48),
    }),
  },
  {
    ...defaults,
    id: 'surrealdb',
    name: 'SurrealDB',
    category: 'database',
    website: 'https://surrealdb.com',
    image: 'surrealdb/surrealdb:latest',
    port: 8000,
    volumes: [{ name: 'data', mountPath: '/data' }],
    healthCheckPath: '/health',
    memoryMb: 512,
    access: { kind: 'login', user: 'root', passwordKey: 'SURREAL_PASS' },
    // The image is just the binary; the shell expands the password at start.
    command: '/surreal start --user root --pass "$SURREAL_PASS" --bind 0.0.0.0:8000 rocksdb:/data/db',
    env: (t) => ({ SURREAL_PASS: t.secret(20) }),
  },

  // ======================================================================= ai
  {
    ...defaults,
    id: 'open-webui',
    name: 'Open WebUI',
    category: 'ai',
    website: 'https://openwebui.com',
    image: 'ghcr.io/open-webui/open-webui:main',
    port: 8080,
    volumes: [{ name: 'data', mountPath: '/app/backend/data' }],
    healthCheckPath: '/health',
    healthCheckTimeoutSec: 600,
    memoryMb: 1024,
    access: { kind: 'setup' },
    featured: true,
    env: (t) => ({ WEBUI_SECRET_KEY: t.secret(32), ...urlEnv(t, 'WEBUI_URL') }),
  },
  {
    ...defaults,
    id: 'ollama',
    name: 'Ollama',
    category: 'ai',
    website: 'https://ollama.com',
    image: 'ollama/ollama:latest',
    port: 11434,
    volumes: [{ name: 'models', mountPath: '/root/.ollama' }],
    healthCheckPath: '/',
    memoryMb: 4096,
    access: { kind: 'open' },
    env: () => ({ OLLAMA_HOST: '0.0.0.0:11434' }),
  },
  {
    ...defaults,
    id: 'librechat',
    name: 'LibreChat',
    category: 'ai',
    website: 'https://www.librechat.ai',
    image: 'ghcr.io/danny-avila/librechat:latest',
    port: 3080,
    volumes: [
      { name: 'images', mountPath: '/app/client/public/images' },
      { name: 'uploads', mountPath: '/app/uploads' },
      { name: 'logs', mountPath: '/app/api/logs' },
    ],
    services: [mongo('7.0')],
    needsUrl: true,
    healthCheckPath: '/health',
    healthCheckTimeoutSec: 300,
    memoryMb: 1024,
    access: { kind: 'setup' },
    env: (t) => ({
      HOST: '0.0.0.0',
      PORT: '3080',
      MONGO_URI: mongoUrl,
      DOMAIN_CLIENT: t.url ?? '',
      DOMAIN_SERVER: t.url ?? '',
      JWT_SECRET: t.hex(32),
      JWT_REFRESH_SECRET: t.hex(32),
      CREDS_KEY: t.hex(32),
      CREDS_IV: t.hex(16),
      ALLOW_REGISTRATION: 'true',
      ALLOW_EMAIL_LOGIN: 'true',
      SEARCH: 'false',
      NO_INDEX: 'true',
    }),
  },
  {
    ...defaults,
    id: 'flowise',
    name: 'Flowise',
    category: 'ai',
    website: 'https://flowiseai.com',
    image: 'flowiseai/flowise:latest',
    port: 3000,
    volumes: [{ name: 'data', mountPath: '/root/.flowise' }],
    services: [postgres()],
    healthCheckPath: '/api/v1/ping',
    healthCheckTimeoutSec: 300,
    memoryMb: 1024,
    access: { kind: 'setup' },
    env: (t) => ({
      PORT: '3000',
      DATABASE_TYPE: 'postgres',
      DATABASE_HOST: pg.host,
      DATABASE_PORT: pg.port,
      DATABASE_NAME: pg.database,
      DATABASE_USER: pg.user,
      DATABASE_PASSWORD: pg.password,
      DATABASE_SSL: 'false',
      FLOWISE_SECRETKEY_OVERWRITE: t.secret(32),
    }),
  },
  {
    ...defaults,
    id: 'anythingllm',
    name: 'AnythingLLM',
    category: 'ai',
    website: 'https://anythingllm.com',
    image: 'mintplexlabs/anythingllm:latest',
    port: 3001,
    volumes: [{ name: 'storage', mountPath: '/app/server/storage' }],
    healthCheckPath: '/api/ping',
    healthCheckTimeoutSec: 300,
    memoryMb: 1024,
    access: { kind: 'setup' },
    env: (t) => ({ STORAGE_DIR: '/app/server/storage', JWT_SECRET: t.secret(32), SERVER_PORT: '3001', DISABLE_TELEMETRY: 'true' }),
  },
  {
    ...defaults,
    id: 'litellm',
    name: 'LiteLLM',
    category: 'ai',
    website: 'https://www.litellm.ai',
    image: 'ghcr.io/berriai/litellm:main-latest',
    port: 4000,
    services: [postgres()],
    healthCheckPath: '/health/liveliness',
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'login', user: 'admin', passwordKey: 'UI_PASSWORD', path: '/ui' },
    env: (t) => ({
      DATABASE_URL: pg.url,
      LITELLM_MASTER_KEY: `sk-${t.secret(32)}`,
      LITELLM_SALT_KEY: `sk-${t.secret(32)}`,
      STORE_MODEL_IN_DB: 'True',
      UI_USERNAME: 'admin',
      UI_PASSWORD: t.secret(16),
    }),
  },
  {
    ...defaults,
    id: 'lobe-chat',
    name: 'LobeChat',
    category: 'ai',
    website: 'https://lobehub.com',
    image: 'lobehub/lobe-chat:latest',
    port: 3210,
    memoryMb: 512,
    access: { kind: 'password', key: 'ACCESS_CODE' },
    env: (t) => ({ ACCESS_CODE: t.secret(16) }),
  },
  {
    ...defaults,
    id: 'jupyter',
    name: 'JupyterLab',
    category: 'ai',
    website: 'https://jupyter.org',
    image: 'quay.io/jupyter/minimal-notebook:latest',
    port: 8888,
    volumes: [{ name: 'work', mountPath: '/home/jovyan/work' }],
    healthCheckPath: '/api',
    healthCheckTimeoutSec: 300,
    memoryMb: 1024,
    access: { kind: 'key', key: 'JUPYTER_TOKEN' },
    env: (t) => ({ JUPYTER_TOKEN: t.secret(32), TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'qdrant',
    name: 'Qdrant',
    category: 'ai',
    website: 'https://qdrant.tech',
    image: 'qdrant/qdrant:latest',
    port: 6333,
    volumes: [{ name: 'storage', mountPath: '/qdrant/storage' }],
    healthCheckPath: '/healthz',
    memoryMb: 512,
    access: { kind: 'key', key: 'QDRANT__SERVICE__API_KEY' },
    env: (t) => ({ QDRANT__SERVICE__API_KEY: t.secret(32) }),
  },
  {
    ...defaults,
    id: 'weaviate',
    name: 'Weaviate',
    category: 'ai',
    website: 'https://weaviate.io',
    image: 'semitechnologies/weaviate:1.30.0',
    port: 8080,
    volumes: [{ name: 'data', mountPath: '/var/lib/weaviate' }],
    healthCheckPath: '/v1/.well-known/ready',
    memoryMb: 1024,
    access: { kind: 'key', key: 'WEAVIATE_API_KEY' },
    env: (t) => ({
      WEAVIATE_API_KEY: t.secret(32),
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate',
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false',
      AUTHENTICATION_APIKEY_ENABLED: 'true',
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: '${WEAVIATE_API_KEY}',
      AUTHENTICATION_APIKEY_USERS: 'admin',
      AUTHORIZATION_ADMINLIST_ENABLED: 'true',
      AUTHORIZATION_ADMINLIST_USERS: 'admin',
      DEFAULT_VECTORIZER_MODULE: 'none',
      CLUSTER_HOSTNAME: 'node1',
      QUERY_DEFAULTS_LIMIT: '25',
    }),
  },
  {
    ...defaults,
    id: 'chroma',
    name: 'Chroma',
    category: 'ai',
    website: 'https://www.trychroma.com',
    image: 'chromadb/chroma:latest',
    port: 8000,
    volumes: [{ name: 'data', mountPath: '/data' }],
    healthCheckPath: '/api/v2/heartbeat',
    memoryMb: 512,
    access: { kind: 'open' },
    env: () => ({ IS_PERSISTENT: 'true', PERSIST_DIRECTORY: '/data', ANONYMIZED_TELEMETRY: 'false' }),
  },

  // ==================================================================== media
  {
    ...defaults,
    id: 'jellyfin',
    name: 'Jellyfin',
    category: 'media',
    website: 'https://jellyfin.org',
    image: 'jellyfin/jellyfin:latest',
    port: 8096,
    volumes: [
      { name: 'config', mountPath: '/config' },
      { name: 'cache', mountPath: '/cache' },
      { name: 'media', mountPath: '/media' },
    ],
    healthCheckPath: '/health',
    healthCheckTimeoutSec: 300,
    memoryMb: 1024,
    access: { kind: 'setup' },
    env: (t) => ({ TZ: t.timezone, ...urlEnv(t, 'JELLYFIN_PublishedServerUrl') }),
  },
  {
    ...defaults,
    id: 'navidrome',
    name: 'Navidrome',
    category: 'media',
    website: 'https://www.navidrome.org',
    image: 'deluan/navidrome:latest',
    port: 4533,
    volumes: [
      { name: 'data', mountPath: '/data' },
      { name: 'music', mountPath: '/music' },
    ],
    healthCheckPath: '/ping',
    memoryMb: 256,
    access: { kind: 'setup' },
    env: (t) => ({ ND_MUSICFOLDER: '/music', ND_DATAFOLDER: '/data', ND_SCANSCHEDULE: '1h', TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'audiobookshelf',
    name: 'Audiobookshelf',
    category: 'media',
    website: 'https://www.audiobookshelf.org',
    image: 'ghcr.io/advplyr/audiobookshelf:latest',
    port: 80,
    volumes: [
      { name: 'config', mountPath: '/config' },
      { name: 'metadata', mountPath: '/metadata' },
      { name: 'audiobooks', mountPath: '/audiobooks' },
      { name: 'podcasts', mountPath: '/podcasts' },
    ],
    healthCheckPath: '/healthcheck',
    memoryMb: 256,
    access: { kind: 'setup' },
    env: (t) => ({ TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'kavita',
    name: 'Kavita',
    category: 'media',
    website: 'https://www.kavitareader.com',
    image: 'jvmilazz0/kavita:latest',
    port: 5000,
    volumes: [
      { name: 'config', mountPath: '/kavita/config' },
      { name: 'library', mountPath: '/library' },
    ],
    healthCheckPath: '/api/health',
    memoryMb: 512,
    access: { kind: 'setup' },
    env: (t) => ({ TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'photoprism',
    name: 'PhotoPrism',
    category: 'media',
    website: 'https://www.photoprism.app',
    image: 'photoprism/photoprism:latest',
    port: 2342,
    volumes: [
      { name: 'storage', mountPath: '/photoprism/storage' },
      { name: 'originals', mountPath: '/photoprism/originals' },
    ],
    services: [mariadb()],
    needsUrl: true,
    healthCheckPath: '/api/v1/status',
    healthCheckTimeoutSec: 600,
    memoryMb: 2048,
    access: { kind: 'login', user: 'admin', passwordKey: 'PHOTOPRISM_ADMIN_PASSWORD' },
    env: (t) => ({
      PHOTOPRISM_ADMIN_USER: 'admin',
      PHOTOPRISM_ADMIN_PASSWORD: t.secret(16),
      PHOTOPRISM_SITE_URL: `${t.url}/`,
      PHOTOPRISM_DATABASE_DRIVER: 'mysql',
      PHOTOPRISM_DATABASE_SERVER: my.hostPort,
      PHOTOPRISM_DATABASE_NAME: my.database,
      PHOTOPRISM_DATABASE_USER: my.user,
      PHOTOPRISM_DATABASE_PASSWORD: my.password,
      PHOTOPRISM_ORIGINALS_LIMIT: '5000',
      PHOTOPRISM_HTTP_COMPRESSION: 'gzip',
      TZ: t.timezone,
    }),
  },
  {
    ...defaults,
    id: 'lychee',
    name: 'Lychee',
    category: 'media',
    website: 'https://lycheeorg.dev',
    image: 'lycheeorg/lychee:latest',
    port: 80,
    volumes: [
      { name: 'conf', mountPath: '/conf' },
      { name: 'uploads', mountPath: '/uploads' },
      { name: 'sym', mountPath: '/sym' },
      { name: 'logs', mountPath: '/logs' },
    ],
    services: [mariadb()],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 512,
    access: { kind: 'setup' },
    env: (t) => ({
      DB_CONNECTION: 'mysql',
      DB_HOST: my.host,
      DB_PORT: my.port,
      DB_DATABASE: my.database,
      DB_USERNAME: my.user,
      DB_PASSWORD: my.password,
      APP_URL: t.url ?? '',
      TRUSTED_PROXIES: '*',
      TIMEZONE: t.timezone,
      PHP_TZ: t.timezone,
    }),
  },
  {
    ...defaults,
    id: 'metube',
    name: 'MeTube',
    category: 'media',
    website: 'https://github.com/alexta69/metube',
    image: 'ghcr.io/alexta69/metube:latest',
    port: 8081,
    volumes: [{ name: 'downloads', mountPath: '/downloads' }],
    memoryMb: 256,
    access: { kind: 'open' },
    env: (t) => ({ TZ: t.timezone }),
  },

  // ================================================================== storage
  {
    ...defaults,
    id: 'nextcloud',
    name: 'Nextcloud',
    category: 'storage',
    website: 'https://nextcloud.com',
    image: 'nextcloud:31-apache',
    port: 80,
    volumes: [{ name: 'html', mountPath: '/var/www/html' }],
    services: [postgres(), redis()],
    needsUrl: true,
    healthCheckPath: '/status.php',
    healthCheckTimeoutSec: 600,
    memoryMb: 1024,
    access: { kind: 'login', user: 'admin', passwordKey: 'NEXTCLOUD_ADMIN_PASSWORD' },
    featured: true,
    env: (t) => ({
      POSTGRES_HOST: pg.hostPort,
      POSTGRES_DB: pg.database,
      POSTGRES_USER: pg.user,
      POSTGRES_PASSWORD: pg.password,
      REDIS_HOST: cache.host,
      REDIS_HOST_PORT: cache.port,
      REDIS_HOST_PASSWORD: cache.password,
      NEXTCLOUD_ADMIN_USER: 'admin',
      NEXTCLOUD_ADMIN_PASSWORD: t.secret(16),
      NEXTCLOUD_TRUSTED_DOMAINS: t.host ?? '',
      OVERWRITEPROTOCOL: t.https ? 'https' : 'http',
      OVERWRITEHOST: t.host ?? '',
      OVERWRITECLIURL: t.url ?? '',
      TRUSTED_PROXIES: '10.0.0.0/8 172.16.0.0/12 192.168.0.0/16',
      PHP_MEMORY_LIMIT: '512M',
      PHP_UPLOAD_LIMIT: '2G',
    }),
  },
  {
    ...defaults,
    id: 'ocis',
    name: 'ownCloud Infinite Scale',
    category: 'storage',
    website: 'https://owncloud.dev',
    image: 'owncloud/ocis:7',
    port: 9200,
    volumes: [
      { name: 'config', mountPath: '/etc/ocis' },
      { name: 'data', mountPath: '/var/lib/ocis' },
    ],
    needsUrl: true,
    healthCheckTimeoutSec: 300,
    memoryMb: 1024,
    access: { kind: 'login', user: 'admin', passwordKey: 'IDM_ADMIN_PASSWORD' },
    // `init` writes the config on the first start and is a no-op afterwards.
    command: 'ocis init || true; ocis server',
    env: (t) => ({
      OCIS_URL: t.url ?? '',
      OCIS_INSECURE: 'true',
      PROXY_TLS: 'false',
      PROXY_HTTP_ADDR: '0.0.0.0:9200',
      OCIS_LOG_LEVEL: 'warn',
      IDM_ADMIN_PASSWORD: t.secret(16),
      IDM_CREATE_DEMO_USERS: 'false',
    }),
  },
  {
    ...defaults,
    id: 'filebrowser',
    name: 'File Browser',
    category: 'storage',
    website: 'https://filebrowser.org',
    image: 'filebrowser/filebrowser:latest',
    port: 80,
    volumes: [
      { name: 'files', mountPath: '/srv' },
      { name: 'database', mountPath: '/database' },
      { name: 'config', mountPath: '/config' },
    ],
    healthCheckPath: '/health',
    memoryMb: 64,
    // The image generates the admin password on the first start and prints it once.
    access: { kind: 'logs' },
    env: (t) => ({ TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'dufs',
    name: 'Dufs',
    category: 'storage',
    website: 'https://github.com/sigoden/dufs',
    image: 'sigoden/dufs:latest',
    port: 5000,
    volumes: [{ name: 'data', mountPath: '/data' }],
    healthCheckPath: '/__dufs__/health',
    memoryMb: 32,
    access: { kind: 'login', user: 'admin', passwordKey: 'DUFS_PASSWORD' },
    command: '/bin/dufs /data -A -a "admin:$DUFS_PASSWORD@/:rw"',
    env: (t) => ({ DUFS_PASSWORD: t.secret(16) }),
  },
  {
    ...defaults,
    id: 'paperless',
    name: 'Paperless-ngx',
    category: 'storage',
    website: 'https://docs.paperless-ngx.com',
    image: 'ghcr.io/paperless-ngx/paperless-ngx:latest',
    port: 8000,
    volumes: [
      { name: 'data', mountPath: '/usr/src/paperless/data' },
      { name: 'media', mountPath: '/usr/src/paperless/media' },
      { name: 'export', mountPath: '/usr/src/paperless/export' },
      { name: 'consume', mountPath: '/usr/src/paperless/consume' },
    ],
    services: [postgres(), redis()],
    needsUrl: true,
    healthCheckTimeoutSec: 600,
    memoryMb: 1024,
    access: { kind: 'login', user: 'admin', passwordKey: 'PAPERLESS_ADMIN_PASSWORD' },
    env: (t) => ({
      PAPERLESS_REDIS: cache.url,
      PAPERLESS_DBHOST: pg.host,
      PAPERLESS_DBPORT: pg.port,
      PAPERLESS_DBNAME: pg.database,
      PAPERLESS_DBUSER: pg.user,
      PAPERLESS_DBPASS: pg.password,
      PAPERLESS_URL: t.url ?? '',
      PAPERLESS_SECRET_KEY: t.secret(48),
      PAPERLESS_ADMIN_USER: 'admin',
      PAPERLESS_ADMIN_PASSWORD: t.secret(16),
      PAPERLESS_TIME_ZONE: t.timezone,
      PAPERLESS_OCR_LANGUAGE: 'eng',
    }),
  },
  {
    ...defaults,
    id: 'send',
    name: 'Send',
    category: 'storage',
    website: 'https://send.vis.ee',
    image: 'registry.gitlab.com/timvisee/send:latest',
    port: 1443,
    volumes: [{ name: 'uploads', mountPath: '/uploads' }],
    services: [redis()],
    needsUrl: true,
    memoryMb: 256,
    access: { kind: 'open' },
    env: (t) => ({
      BASE_URL: t.url ?? '',
      PORT: '1443',
      REDIS_HOST: cache.host,
      REDIS_PORT: cache.port,
      REDIS_PASSWORD: cache.password,
      FILE_DIR: '/uploads',
      MAX_FILE_SIZE: '2147483648',
      MAX_EXPIRE_SECONDS: '604800',
    }),
  },

  // ================================================================= security
  {
    ...defaults,
    id: 'vaultwarden',
    name: 'Vaultwarden',
    category: 'security',
    website: 'https://github.com/dani-garcia/vaultwarden',
    image: 'vaultwarden/server:latest',
    port: 80,
    volumes: [{ name: 'data', mountPath: '/data' }],
    needsUrl: true,
    healthCheckPath: '/alive',
    memoryMb: 128,
    access: { kind: 'setup' },
    featured: true,
    env: (t) => ({ DOMAIN: t.url ?? '', SIGNUPS_ALLOWED: 'true' }),
  },
  {
    ...defaults,
    id: 'keycloak',
    name: 'Keycloak',
    category: 'security',
    website: 'https://www.keycloak.org',
    image: 'quay.io/keycloak/keycloak:latest',
    port: 8080,
    services: [postgres()],
    needsUrl: true,
    healthCheckTimeoutSec: 600,
    memoryMb: 1024,
    access: { kind: 'login', user: 'admin', passwordKey: 'KC_BOOTSTRAP_ADMIN_PASSWORD', path: '/admin' },
    // The image has no default command: `start` runs the production server.
    command: '/opt/keycloak/bin/kc.sh start',
    env: (t) => ({
      KC_DB: 'postgres',
      KC_DB_URL: pg.jdbc,
      KC_DB_USERNAME: pg.user,
      KC_DB_PASSWORD: pg.password,
      KC_BOOTSTRAP_ADMIN_USERNAME: 'admin',
      KC_BOOTSTRAP_ADMIN_PASSWORD: t.secret(16),
      KC_HOSTNAME: t.url ?? '',
      KC_HTTP_ENABLED: 'true',
      KC_PROXY_HEADERS: 'xforwarded',
    }),
  },
  {
    ...defaults,
    id: 'pocket-id',
    name: 'Pocket ID',
    category: 'security',
    website: 'https://pocket-id.org',
    image: 'ghcr.io/pocket-id/pocket-id:latest',
    port: 1411,
    volumes: [{ name: 'data', mountPath: '/app/data' }],
    needsUrl: true,
    healthCheckPath: '/healthz',
    memoryMb: 128,
    access: { kind: 'setup', path: '/setup' },
    env: (t) => ({ APP_URL: t.url ?? '', TRUST_PROXY: 'true', ENCRYPTION_KEY: t.base64(32) }),
  },
  {
    ...defaults,
    id: 'infisical',
    name: 'Infisical',
    category: 'security',
    website: 'https://infisical.com',
    image: 'infisical/infisical:latest-postgres',
    port: 8080,
    services: [postgres(), redis()],
    needsUrl: true,
    healthCheckPath: '/api/status',
    healthCheckTimeoutSec: 300,
    memoryMb: 1024,
    access: { kind: 'setup' },
    env: (t) => ({
      SITE_URL: t.url ?? '',
      DB_CONNECTION_URI: pg.url,
      REDIS_URL: cache.url,
      ENCRYPTION_KEY: t.hex(16),
      AUTH_SECRET: t.base64(32),
      TELEMETRY_ENABLED: 'false',
    }),
  },

  // ==================================================================== tools
  {
    ...defaults,
    id: 'it-tools',
    name: 'IT Tools',
    category: 'tools',
    website: 'https://it-tools.tech',
    image: 'corentinth/it-tools:latest',
    port: 80,
    memoryMb: 32,
    access: { kind: 'open' },
    env: () => ({}),
  },
  {
    ...defaults,
    id: 'excalidraw',
    name: 'Excalidraw',
    category: 'tools',
    website: 'https://excalidraw.com',
    image: 'excalidraw/excalidraw:latest',
    port: 80,
    memoryMb: 32,
    access: { kind: 'open' },
    env: () => ({}),
  },
  {
    ...defaults,
    id: 'stirling-pdf',
    name: 'Stirling PDF',
    category: 'tools',
    website: 'https://www.stirlingpdf.com',
    image: 'stirlingtools/stirling-pdf:latest',
    port: 8080,
    healthCheckTimeoutSec: 300,
    memoryMb: 1024,
    access: { kind: 'open' },
    env: () => ({}),
  },
  {
    ...defaults,
    id: 'cyberchef',
    name: 'CyberChef',
    category: 'tools',
    website: 'https://gchq.github.io/CyberChef',
    image: 'ghcr.io/gchq/cyberchef:latest',
    port: 80,
    memoryMb: 32,
    access: { kind: 'open' },
    env: () => ({}),
  },
  {
    ...defaults,
    id: 'drawio',
    name: 'draw.io',
    category: 'tools',
    website: 'https://www.drawio.com',
    image: 'jgraph/drawio:latest',
    port: 8080,
    healthCheckTimeoutSec: 300,
    memoryMb: 256,
    access: { kind: 'open' },
    env: () => ({}),
  },
  {
    ...defaults,
    id: 'privatebin',
    name: 'PrivateBin',
    category: 'tools',
    website: 'https://privatebin.info',
    image: 'privatebin/nginx-fpm-alpine:latest',
    port: 8080,
    volumes: [{ name: 'data', mountPath: '/srv/data' }],
    memoryMb: 64,
    access: { kind: 'open' },
    env: (t) => ({ TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'omni-tools',
    name: 'OmniTools',
    category: 'tools',
    website: 'https://omnitools.app',
    image: 'iib0011/omni-tools:latest',
    port: 80,
    memoryMb: 64,
    access: { kind: 'open' },
    env: () => ({}),
  },
  {
    ...defaults,
    id: 'librespeed',
    name: 'LibreSpeed',
    category: 'tools',
    website: 'https://librespeed.org',
    image: 'lscr.io/linuxserver/librespeed:latest',
    port: 80,
    memoryMb: 64,
    access: { kind: 'open' },
    env: (t) => linuxserver(t),
  },
  {
    ...defaults,
    id: 'pairdrop',
    name: 'PairDrop',
    category: 'tools',
    website: 'https://pairdrop.net',
    image: 'lscr.io/linuxserver/pairdrop:latest',
    port: 3000,
    memoryMb: 64,
    access: { kind: 'open' },
    env: (t) => ({ ...linuxserver(t), RATE_LIMIT: 'false' }),
  },
  {
    ...defaults,
    id: 'searxng',
    name: 'SearXNG',
    category: 'tools',
    website: 'https://docs.searxng.org',
    image: 'searxng/searxng:latest',
    port: 8080,
    volumes: [{ name: 'config', mountPath: '/etc/searxng' }],
    needsUrl: true,
    healthCheckPath: '/healthz',
    memoryMb: 256,
    access: { kind: 'open' },
    env: (t) => ({ SEARXNG_BASE_URL: `${t.url}/`, SEARXNG_SECRET: t.secret(32) }),
  },
  {
    ...defaults,
    id: 'homarr',
    name: 'Homarr',
    category: 'tools',
    website: 'https://homarr.dev',
    image: 'ghcr.io/homarr-labs/homarr:latest',
    port: 7575,
    volumes: [{ name: 'data', mountPath: '/appdata' }],
    healthCheckPath: '/api/health/ready',
    healthCheckTimeoutSec: 300,
    memoryMb: 256,
    access: { kind: 'setup' },
    env: (t) => ({ SECRET_ENCRYPTION_KEY: t.hex(32), TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'homepage',
    name: 'Homepage',
    category: 'tools',
    website: 'https://gethomepage.dev',
    image: 'ghcr.io/gethomepage/homepage:latest',
    port: 3000,
    volumes: [{ name: 'config', mountPath: '/app/config' }],
    memoryMb: 128,
    access: { kind: 'open' },
    env: (t) => ({ HOMEPAGE_ALLOWED_HOSTS: t.host ?? '*', TZ: t.timezone }),
  },
  {
    ...defaults,
    id: 'dashy',
    name: 'Dashy',
    category: 'tools',
    website: 'https://dashy.to',
    image: 'lissy93/dashy:latest',
    port: 8080,
    volumes: [{ name: 'data', mountPath: '/app/user-data' }],
    healthCheckTimeoutSec: 300,
    memoryMb: 256,
    access: { kind: 'open' },
    env: () => ({}),
  },
  {
    ...defaults,
    id: 'shlink',
    name: 'Shlink',
    category: 'tools',
    website: 'https://shlink.io',
    image: 'shlinkio/shlink:stable',
    port: 8080,
    services: [postgres()],
    needsUrl: true,
    healthCheckPath: '/rest/health',
    memoryMb: 256,
    access: { kind: 'key', key: 'INITIAL_API_KEY' },
    env: (t) => ({
      DEFAULT_DOMAIN: t.host ?? '',
      IS_HTTPS_ENABLED: String(t.https),
      INITIAL_API_KEY: t.secret(32),
      DB_DRIVER: 'postgres',
      DB_HOST: pg.host,
      DB_PORT: pg.port,
      DB_NAME: pg.database,
      DB_USER: pg.user,
      DB_PASSWORD: pg.password,
      TIMEZONE: t.timezone,
    }),
  },
  {
    ...defaults,
    id: 'yourls',
    name: 'YOURLS',
    category: 'tools',
    website: 'https://yourls.org',
    image: 'yourls:latest',
    port: 80,
    volumes: [{ name: 'html', mountPath: '/var/www/html' }],
    services: [mysql()],
    needsUrl: true,
    memoryMb: 128,
    access: { kind: 'login', user: 'admin', passwordKey: 'YOURLS_PASS', path: '/admin/' },
    env: (t) => ({
      YOURLS_DB_HOST: my.hostPort,
      YOURLS_DB_USER: my.user,
      YOURLS_DB_PASS: my.password,
      YOURLS_DB_NAME: my.database,
      YOURLS_SITE: t.url ?? '',
      YOURLS_USER: 'admin',
      YOURLS_PASS: t.secret(16),
    }),
  },
];

export function findTemplate(id: string): TemplateDefinition | undefined {
  return TEMPLATES.find((template) => template.id === id);
}
